- hosts: 127.0.0.1
  connection: local
  become: true

  tasks:
  - name: dynamic hostname group
    group_by:
      key: "{{ansible_hostname}}"
    changed_when: False

  - name: Apply Roles
    include_role:
      name: "{{role}}"
    loop: "{{roles}}"
    loop_control:
      loop_var: role
    when: roles
